language: julia

os:
  - linux
  - osx

julia:
  - 0.5
  - nightly

matrix:
  include:
    - branch: master
      os: osx
      julia: 0.5
    - os: linux
  allow_failures:
    - julia: nightly  
  fast_finish: true

sudo:
 false

install:
  # DataStructures is for the benchmarking script
  - julia -e 'Pkg.add("DataStructures"); Pkg.clone(pwd(), "CountMin")'

script:
  - julia -e 'Pkg.test("CountMin")'
  - julia misc/cms.jl
