language: julia

julia:
 - 0.5
 - nightly

sudo:
 false

install:
  # DataStructures is for the benchmarking script
  - julia -e 'Pkg.add("DataStructures"); Pkg.clone(pwd(), "CountMin")'

script:
  - julia -e 'Pkg.test("CountMin")'
  - julia misc/cms.jl
